import os
import sys

# Ensure the backend directory is in sys.path
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from sqlalchemy import text

from app.core.database import SessionLocal, init_db
from app.models.cafe import Cafe


def seed_cafes():
    db = SessionLocal()

    # Force seeding by commenting out checking if cafes already exist
    cafes_data = [
        {
            "name": "Himalayan Java Coffee",
            "area": "Thamel",
            "city": "Kathmandu",
            "address": "Mandala Street, Thamel, Kathmandu",
            "description": "A classic spot in Thamel known for excellent coffee, locally grown beans, a cozy ambiance, and great pastries.",
            "rating": 0.0,
            "price_level": "$$",
            "has_wifi": True,
            "has_outdoor": True,
            "good_for_work": True,
            "image_url": "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800&q=80",
            "wifi_speed": "Fast",
            "plug_rating": 0.0,
            "vibe_tags": ["#Classic", "#DeepWork", "#GroupMeetings"],
            "lat": 27.7146,
            "lng": 85.3121,
        },
        {
            "name": "Kar.Ma Coffee",
            "area": "Jhamsikhel",
            "city": "Lalitpur",
            "address": "Gyan Mandal, Jhamsikhel, Lalitpur",
            "description": "An eco-friendly, aesthetic boutique cafe known for fair-trade coffee and artisanal crafts.",
            "rating": 0.0,
            "price_level": "$$",
            "has_wifi": True,
            "has_outdoor": False,
            "good_for_work": True,
            "image_url": "https://images.unsplash.com/photo-1511920170033-f8396924c348?w=800&q=80",
            "wifi_speed": "Fast",
            "plug_rating": 0.0,
            "vibe_tags": ["#Aesthetic", "#DeepWork", "#Quiet"],
            "lat": 27.6744,
            "lng": 85.3129,
        },
        {
            "name": "Bia Cafe",
            "area": "Boudha",
            "city": "Kathmandu",
            "address": "Boudha Stupa, Kathmandu",
            "description": "A beautiful view of the Stupa with a calming environment. Perfect for reading, relaxing, or a casual date.",
            "rating": 0.0,
            "price_level": "$$",
            "has_wifi": True,
            "has_outdoor": True,
            "good_for_work": False,
            "image_url": "https://images.unsplash.com/photo-1497935586351-b67a49e012bf?w=800&q=80",
            "wifi_speed": "Average",
            "plug_rating": 0.0,
            "vibe_tags": ["#DateNight", "#Aesthetic", "#Chatty"],
            "lat": 27.7215,
            "lng": 85.3598,
        },
        {
            "name": "Cafe Soma",
            "area": "Baluwatar",
            "city": "Kathmandu",
            "address": "Baluwatar, Kathmandu",
            "description": "A quiet, book-filled space that serves wonderful breakfasts and single-origin coffee.",
            "rating": 0.0,
            "price_level": "$$",
            "has_wifi": True,
            "has_outdoor": False,
            "good_for_work": True,
            "image_url": "https://images.unsplash.com/photo-1515823662972-da6a2e4d3002?w=800&q=80",
            "wifi_speed": "Fast",
            "plug_rating": 0.0,
            "vibe_tags": ["#DeepWork", "#Quiet", "#Books"],
            "lat": 27.7289,
            "lng": 85.3255,
        },
        {
            "name": "Moondrop Cafe",
            "area": "Patan",
            "city": "Lalitpur",
            "address": "Patan Durbar Square, Lalitpur",
            "description": "Tucked in the alleys of Patan, a great hangout spot with amazing latte art and historic architecture views.",
            "rating": 0.0,
            "price_level": "$$",
            "has_wifi": True,
            "has_outdoor": True,
            "good_for_work": False,
            "image_url": "https://images.unsplash.com/photo-1600093463592-8e36ae95ef56?w=800&q=80",
            "wifi_speed": "Average",
            "plug_rating": 0.0,
            "vibe_tags": ["#Chatty", "#GroupMeetings", "#Aesthetic"],
            "lat": 27.6727,
            "lng": 85.3253,
        },
        {
            "name": "Evoke Cafe & Bistro",
            "area": "Jhamsikhel",
            "city": "Lalitpur",
            "address": "Jhamsikhel, Lalitpur",
            "description": "A lively bistro with an impressive outdoor garden, perfect for weekend brunches and evening cocktails.",
            "rating": 0.0,
            "price_level": "$$$",
            "has_wifi": True,
            "has_outdoor": True,
            "good_for_work": True,
            "image_url": "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800&q=80",
            "wifi_speed": "Fast",
            "plug_rating": 0.0,
            "vibe_tags": ["#Chic", "#Outdoor", "#Brunch"],
            "lat": 27.6710,
            "lng": 85.3130,
        },
        {
            "name": "Bodhi Books and Bakes",
            "area": "Maharajgunj",
            "city": "Kathmandu",
            "address": "Maharajgunj, Kathmandu",
            "description": "A sanctuary for book lovers. Sip fantastic local coffee while surrounded by walls of literature.",
            "rating": 0.0,
            "price_level": "$$",
            "has_wifi": True,
            "has_outdoor": False,
            "good_for_work": True,
            "image_url": "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800&q=80",
            "wifi_speed": "Fast",
            "plug_rating": 0.0,
            "vibe_tags": ["#Books", "#Quiet", "#DeepWork"],
            "lat": 27.7370,
            "lng": 85.3323,
        },
        {
            "name": "Chikusa Cafe",
            "area": "Thamel",
            "city": "Kathmandu",
            "address": "Amrit Marg, Thamel",
            "description": "Known for having the best crepes and filter coffee in town. A tiny, minimalist gem hidden in the busy streets.",
            "rating": 0.0,
            "price_level": "$",
            "has_wifi": False,
            "has_outdoor": False,
            "good_for_work": False,
            "image_url": "https://images.unsplash.com/photo-1521017430205-959baefa1a5d?w=800&q=80",
            "wifi_speed": "None",
            "plug_rating": 0.0,
            "vibe_tags": ["#HiddenGem", "#Breakfast", "#Intimate"],
            "lat": 27.7153,
            "lng": 85.3105,
        },
        {
            "name": "Yellow Pomelo",
            "area": "Jawalakhel",
            "city": "Lalitpur",
            "address": "Jawalakhel, Lalitpur",
            "description": "Chilled out terrace cafe with excellent Asian fusion food, craft coffee, and a very relaxing evening vibe.",
            "rating": 0.0,
            "price_level": "$$$",
            "has_wifi": True,
            "has_outdoor": True,
            "good_for_work": False,
            "image_url": "https://images.unsplash.com/photo-1525610553991-2bede1a236e2?w=800&q=80",
            "wifi_speed": "Average",
            "plug_rating": 0.0,
            "vibe_tags": ["#DateNight", "#Outdoor", "#Fusion"],
            "lat": 27.6738,
            "lng": 85.3162,
        },
        {
            "name": "Flat Iron Grill",
            "area": "Lazimpat",
            "city": "Kathmandu",
            "address": "Lazimpat, Kathmandu",
            "description": "More than just a grill, their attached cafe section offers bright natural light and excellent espresso options.",
            "rating": 0.0,
            "price_level": "$$",
            "has_wifi": True,
            "has_outdoor": True,
            "good_for_work": True,
            "image_url": "https://images.unsplash.com/photo-1559925393-8be0ec4767c8?w=800&q=80",
            "wifi_speed": "Fast",
            "plug_rating": 0.0,
            "vibe_tags": ["#Business", "#Lunch", "#DeepWork"],
            "lat": 27.7225,
            "lng": 85.3193,
        },
        {
            "name": "Top of the World Coffee",
            "area": "Jhamsikhel",
            "city": "Lalitpur",
            "address": "Jhamsikhel, Lalitpur",
            "description": "A very quiet, simple setting that focuses purely on roasting and serving exceptionally high-quality origin beans.",
            "rating": 0.0,
            "price_level": "$",
            "has_wifi": True,
            "has_outdoor": False,
            "good_for_work": True,
            "image_url": "https://images.unsplash.com/photo-1498804103079-a6351b050096?w=800&q=80",
            "wifi_speed": "Fast",
            "plug_rating": 0.0,
            "vibe_tags": ["#CoffeeSnob", "#Quiet", "#Minimal"],
            "lat": 27.6766,
            "lng": 85.3119,
        },
        {
            "name": "The Bakery Cafe",
            "area": "Dharahara",
            "city": "Kathmandu",
            "address": "Sundhara, Kathmandu",
            "description": "A bustling staple in Kathmandu. Known for employing differently-abled staff and serving amazing momos alongside coffee.",
            "rating": 0.0,
            "price_level": "$$",
            "has_wifi": True,
            "has_outdoor": False,
            "good_for_work": False,
            "image_url": "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&q=80",
            "wifi_speed": "Slow",
            "plug_rating": 0.0,
            "vibe_tags": ["#Classic", "#Chatty", "#Inclusive"],
            "lat": 27.7006,
            "lng": 85.3129,
        },
        {
            "name": "Moina Cafe",
            "area": "Bakhundole",
            "city": "Lalitpur",
            "address": "Bakhundole, Lalitpur",
            "description": "A gorgeous hidden courtyard offering an escape from the city dust, surrounded by greenery and soft lighting.",
            "rating": 0.0,
            "price_level": "$$",
            "has_wifi": True,
            "has_outdoor": True,
            "good_for_work": True,
            "image_url": "https://images.unsplash.com/photo-1453614512568-c4024d13c247?w=800&q=80",
            "wifi_speed": "Fast",
            "plug_rating": 0.0,
            "vibe_tags": ["#Greenery", "#Aesthetic", "#Escape"],
            "lat": 27.6784,
            "lng": 85.3150,
        },
        {
            "name": "Anantara Coffee",
            "area": "Boudha",
            "city": "Kathmandu",
            "address": "Fulbari, Boudha",
            "description": "A serene, beautifully designed cafe located just minutes from the Stupa. Perfect for journaling or relaxed conversation.",
            "rating": 0.0,
            "price_level": "$$",
            "has_wifi": True,
            "has_outdoor": True,
            "good_for_work": True,
            "image_url": "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&q=80",
            "wifi_speed": "Fast",
            "plug_rating": 0.0,
            "vibe_tags": ["#Zen", "#DeepWork", "#Aesthetic"],
            "lat": 27.7230,
            "lng": 85.3615,
        },
        {
            "name": "Dhokaima Cafe",
            "area": "Patan Dhoka",
            "city": "Lalitpur",
            "address": "Patan Dhoka, Lalitpur",
            "description": "A beloved institution under the Patan Dhoka gate. Historic brick setting, great chocolate cake, and excellent ambiance.",
            "rating": 0.0,
            "price_level": "$$",
            "has_wifi": True,
            "has_outdoor": True,
            "good_for_work": False,
            "image_url": "https://images.unsplash.com/photo-1559304787-83344db60667?w=800&q=80",
            "wifi_speed": "Average",
            "plug_rating": 0.0,
            "vibe_tags": ["#Historic", "#Chatty", "#Courtyard"],
            "lat": 27.6800,
            "lng": 85.3188,
        }
    ]

    # First clean out the old ones
    db.execute(text("SET FOREIGN_KEY_CHECKS=0;"))
    db.query(Cafe).delete()

    for data in cafes_data:
        cafe = Cafe(**data)
        db.add(cafe)

    db.commit()
    db.execute(text("SET FOREIGN_KEY_CHECKS=1;"))
    print(f"Successfully seeded {len(cafes_data)} cafes!")
    db.close()


if __name__ == "__main__":
    init_db()
    seed_cafes()
